#! /bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 <input_html_file>"
    exit 1
fi

input="$1"
max_depth=4
for i in $(seq 0 $max_depth); do
    output="${input%.html}-depth-$i.html"
    cp $input $output
    for j in $(seq $i); do sed -i 's/href="/href="..\//' "$output"; done
    for j in $(seq $i); do sed -i 's/src="/src="..\//' "$output"; done
done
