[book]
title = "tatarcham / онлайн учебник татарского языка"
authors = ["Ayzat Rizatdinov (https://github.com/dov4k1n)"]
language = "ru"
multilingual = false
src = "src"

[output.html]
smart-punctuation = true
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/dov4k1n/dov4k1n.github.io"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/dov4k1n/dov4k1n.github.io/edit/main/book/{path}"

[output.html.print]
enable = true
page-break = false